import { WorkerAttendance } from "./worker_attendance";

export interface Reading {
    id?: number,
    read_at?: string,
    temperature: number,
    humidity: number,
    brightness: number,
    methane: boolean,
    carbon_monoxide: boolean,
    smoke_detection: boolean,
    uses_welding_protection: boolean,
    uses_gas_protection: boolean,
    avg_X: number,
    avg_Y: number,
    avg_Z: number,
    avg_G: number,
    std_X: number,
    std_Y: number,
    std_Z: number,
    std_G: number,
    max_G: number,
    incorrect_posture: number,
    anomaly: boolean,
    attendance_id?: number,
    anomalous_temperature: boolean,
    anomalous_humidity: boolean,
    anomalous_brightness: boolean,
    anomalous_max_g: boolean,
    anomalous_posture: boolean,
    weather_temperature_max: number,
    weather_temperature_min: number, 
    weather_temperature: number,
    weather_humidity: number,
    weather_brightness: number,
    WorkerAttendance?: WorkerAttendance
}